// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManagerAPI.Infrastructure.Data;

#nullable disable

namespace TaskManagerAPI.Infrastructure.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("TaskManagerAPI.Core.Entities.ApplicationUser", b =>
        {
            b.Property<string>("Id").HasColumnType("nvarchar(450)");
            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
            b.Property<string>("Email").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
            b.Property<string>("PasswordHash").IsRequired().HasColumnType("nvarchar(max)");
            b.Property<string>("Role").IsRequired().HasMaxLength(20).HasDefaultValue("User").HasColumnType("nvarchar(20)");
            b.Property<string>("UserName").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.HasKey("Id");
            b.HasIndex("Email").IsUnique();
            b.HasIndex("UserName").IsUnique();
            b.ToTable("Users");
        });

        modelBuilder.Entity("TaskManagerAPI.Core.Entities.TaskItem", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
            b.Property<string>("Description").HasMaxLength(2000).HasColumnType("nvarchar(2000)");
            b.Property<string>("Priority").IsRequired().HasMaxLength(20).HasDefaultValue("Medium").HasColumnType("nvarchar(20)");
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasDefaultValue("Pending").HasColumnType("nvarchar(20)");
            b.Property<string>("Title").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
            b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
            b.Property<string>("UserId").IsRequired().HasColumnType("nvarchar(450)");
            b.HasKey("Id");
            b.HasIndex("Priority");
            b.HasIndex("Status");
            b.HasIndex("UserId");
            b.ToTable("Tasks");
        });

        modelBuilder.Entity("TaskManagerAPI.Core.Entities.TaskItem", b =>
        {
            b.HasOne("TaskManagerAPI.Core.Entities.ApplicationUser", "User")
             .WithMany("Tasks")
             .HasForeignKey("UserId")
             .OnDelete(DeleteBehavior.Cascade)
             .IsRequired();
            b.Navigation("User");
        });

        modelBuilder.Entity("TaskManagerAPI.Core.Entities.ApplicationUser", b =>
        {
            b.Navigation("Tasks");
        });
#pragma warning restore 612, 618
    }
}
